accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.get_profile, name='get_profile'),
    path('settings/', views.settings, name='settings'),
    path('statistics/', views.statistics, name='statistics'),
    path('statistic_dict/<int:dict_id>/', views.statistic_dict, name='statistic_dict'),
]

dictionaries/urls.py
from django.urls import path

from . import views

app_name = 'dictionaries'
urlpatterns = [
    path('create_dictionary/', views.create_dictionary, name='create_dictionary'),
    path('update_dictionary/<int:dictionary_id>/', views.update_dictionary, name='update_dictionary'),
]

foreign_words/urls.py
from django.contrib import admin
from django.urls import path, include

from foreign_words import views

urlpatterns = [
    path('', views.main_page),
    path('help/', views.help_page),
    path('admin/', admin.site.urls),
    path('tasks/', include(('tasks.urls', 'tasks'), namespace='tasks')),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
    path('dictionaries/', include(('dictionaries.urls', 'dictionaries'), namespace='dictionaries')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('accounts.urls')),
]

groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'
urlpatterns = [
    path('', views.get_groups, name='get_groups'),
    path('create_group/', views.create_group, name='create_group'),

    path('<int:group_id>', views.group_page, name='group_page'),
    path('<int:group_id>/join_group/', views.join_group, name='join_group'),
    path('<int:group_id>/leave_group/', views.leave_group, name='leave_group'),
    path('<int:group_id>/participants/', views.group_participants, name='participants'),
    path('<int:group_id>/add_student/', views.add_student, name='add_student'),
    path('<int:group_id>/dictionaries/', views.choose_group_dictionary, name='group_dictionaries'),
    path('<int:group_id>/create_dictionary/', views.create_group_dictionary, name='create_group_dictionary'),
    path('<int:group_id>/create_task/', views.create_task, name='create_task'),
    path('<int:group_id>/delete_task/<int:task_id>', views.delete_task, name='delete_task'),

    path('<int:group_id>/rating/', views.get_rating_data, name='get_rating_data'),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('choose_dictionary/', views.choose_dictionary, name='exercises'),

    path('create_exercise/<int:dict_id>/', views.create_exercise, name='create_exercise'),

    path('training/<int:pk>/', views.training, name='training'),
    path('training/<int:pk>/next', views.training_next, name='training_next'),
    path('training/<int:pk>/result', views.show_results, name='show_results'),

    path('trial/<int:pk>/', views.trial, name='trial'),
    path('trial/<int:pk>/next', views.trial_next, name='trial_next'),
    path('trial/<int:pk>/result', views.show_trial_results, name='show_trial_results'),
]

templates/exercises/choose_dictionary.html
{% extends "base.html" %}
{% block left_colon %}
    <div class="links-div container">
        {% if group %}
        <div class="row">
            <a class="left-colon-link" href="{% url 'groups:group_page' group.id %}">Back to group page</a>
        </div>
        {% endif %}
        <div class="row">
            <a class="left-colon-link active" href="{% url 'tasks:exercises' %}">Choose dictionary</a>
        </div>
        {% if group %}
        <div class="row">
            <a class="left-colon-link" href={% url 'groups:create_group_dictionary' group.id %}>Create dictionary</a>
        </div>
        {% else %}
        <div class="row">
            <a class="left-colon-link" href={% url 'dictionaries:create_dictionary' %}>Create dictionary</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href={% url 'accounts:statistics' %}>Statistics</a>
        </div>
        {% endif %}
    </div>
{% endblock %}
{% block head_title %}
Choose a dictionary
{% endblock %}
{% block content %}
    <div class="container">
    {% if dictionaries|length > 0 %}
    <h4>Dictionaries:</h4>
        {% for dictionary in dictionaries %}
            <div class="row dict-box">
                <div class="container">
                <div class="row">
                    <div class="col-9">
                        <div class="row">
                            <a class="dict-link" href="{% url 'tasks:create_exercise' dictionary.id %}">{{ dictionary.title }}</a>
                        </div>
                        {% if dictionary.description|length > 0 %}
                        <div class="row small">
                            {{ dictionary.description }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-3">
                        <div class="row">
                        <input class="btn btn-outline-success" type="button" value="Choose"
                               onclick="openDictionary({{ dictionary.id }})">
                        </div>
                        <div class="row">
                            <input class="btn btn-outline-secondary" type="button" value="Update"
                                   onclick="updateDictionary({{ dictionary.id }})">
                        </div>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        No dictionaries
    {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
    function openDictionary(dictionary_id) {
        document.location.href = '/tasks/create_exercise/' + dictionary_id + '/';
    }

    function updateDictionary(dictionary_id) {
        document.location.href = '/dictionaries/update_dictionary/' + dictionary_id + '/';
    }

    $(document).ready(function() {
        $('li#dictionaries a').addClass('active');
    });
    </script>
{% endblock %}

templates/exercises/create_exercise.html
{% extends "base.html" %}
{% block head_title %} Create exercise {% endblock %}
{% block content %}
    <div class="container my-form-container">
    <div class="container">
        <h1>Create exercise</h1>
        <form action="" method="post" enctype="multipart/form-data" data-ajax="false">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="row">
                <div class="col-5">
                    <div class="row">
                        <button class="btn btn-sm btn-outline-primary" type="submit">Submit</button>
                    </div>
                </div>
                <div class="col-2"></div>
                <div class="col-5">
                    <div class="row">
                        <button class="btn btn-sm btn-outline-danger" type="reset">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#dictionaries a').addClass('active');
        });
    </script>
{% endblock %}