accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.get_profile, name='get_profile'),
    path('settings/', views.settings, name='settings'),
    path('statistics/', views.statistics, name='statistics'),
    path('statistic_dict/<int:dict_id>/', views.statistic_dict, name='statistic_dict'),
]

foreign_words/urls.py
from django.contrib import admin
from django.urls import path, include

from foreign_words import views

urlpatterns = [
    path('', views.main_page),
    path('help/', views.help_page),
    path('admin/', admin.site.urls),
    path('tasks/', include(('tasks.urls', 'tasks'), namespace='tasks')),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
    path('dictionaries/', include(('dictionaries.urls', 'dictionaries'), namespace='dictionaries')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('accounts.urls')),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('choose_dictionary/', views.choose_dictionary, name='exercises'),

    path('create_exercise/<int:dict_id>/', views.create_exercise, name='create_exercise'),

    path('training/<int:pk>/', views.training, name='training'),
    path('training/<int:pk>/next', views.training_next, name='training_next'),
    path('training/<int:pk>/result', views.show_results, name='show_results'),

    path('trial/<int:pk>/', views.trial, name='trial'),
    path('trial/<int:pk>/next', views.trial_next, name='trial_next'),
    path('trial/<int:pk>/result', views.show_trial_results, name='show_trial_results'),
]

accounts/views.py
from operator import itemgetter

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_http_methods

from dictionaries.models import Dictionary, Word
from tasks.models import TrainingExercise, TrialExercise
from tasks.models import get_statistic_list, Statistic


@login_required
@require_GET
def get_profile(request):
    user: User = request.user
    trials: list[TrialExercise] = [task for task in TrialExercise.objects.filter(creator=user).all()
                                   if not task.is_finished]
    trials_id: list[int] = [trial.id for trial in trials]
    trainings: list[TrainingExercise] = [task for task in TrainingExercise.objects.filter(creator=user).all()
                                         if not task.is_finished and task.id not in trials_id]
    return render(request, 'accounts/profile.html', {'user': user,
                                                     'unfinished_trainings': trainings,
                                                     'unfinished_trials': trials,
                                                     })


@login_required
@require_http_methods(['GET', 'POST'])
def settings(request):
    user: User = request.user
    if request.method == 'GET':
        return render(request, 'accounts/settings.html', {'user': user})
    elif request.method == 'POST':
        new_username: str = request.POST['username']
        new_firstname: str = request.POST['firstname']
        new_lastname: str = request.POST['lastname']
        user.username = new_username
        user.first_name = new_firstname
        user.last_name = new_lastname
        user.save()
        messages.add_message(request, messages.INFO, 'All changes was saved')
        my_messages = list(map(lambda msg: msg.message, messages.get_messages(request)))
        print(my_messages)
        return JsonResponse({'my_messages': my_messages})


@login_required
@require_GET
def statistics(request):
    user: User = request.user
    used_dicts: set[Dictionary] = {exercise.dictionary
                                   for exercise in TrainingExercise.objects.filter(creator=user)
                                   if exercise.dictionary}
    return render(request, 'accounts/statistics_dict.html', {
        'user': user,
        'dictionaries': list(used_dicts)
    })


@login_required
@require_GET
def statistic_dict(request, dict_id):
    user: User = request.user
    dictionary: Dictionary = Dictionary.objects.get(id=dict_id)
    trials: list[TrialExercise] = list(TrialExercise.objects.filter(creator=user, dictionary=dictionary))
    trials_id: list[int] = [trial.id for trial in trials]
    trainings: list[TrainingExercise] = [exercise for exercise in
                                         TrainingExercise.objects.filter(creator=user, dictionary=dictionary)
                                         if exercise.id not in trials_id]
    training_words: dict[Word, Statistic] = {Word.objects.get(id=word_id): statistic
                                             for word_id, statistic in get_statistic_list(trainings).items()}
    trial_words: dict[Word, Statistic] = {Word.objects.get(id=word_id): statistic
                                          for word_id, statistic in get_statistic_list(trials).items()}
    return render(request, 'accounts/statistics.html', {
        'user': user,
        'trial_words': sorted(trial_words.items(), key=itemgetter(0)),
        'training_words': sorted(training_words.items(), key=itemgetter(0)),
        'language1': dictionary.languages[0],
        'language2': dictionary.languages[1]
    })

templates/accounts/profile.html
{% extends "base.html" %}
{% block head_title %}
    Profile
{% endblock %}
{% block left_colon %}
    <div class="container links-div">
        <div class="row">
            <a class="left-colon-link active" href="{% url 'accounts:get_profile' %}">Profile</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="/groups/">Groups</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:statistics' %}">Statistics</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:settings' %}">Settings</a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2>Hello, {{ user.username }}!</h2>
        </div>
        {% if unfinished_trainings|length > 0 %}
        <div class="row unfinished_trainings">
            <h4>Unfinished trainings:</h4>
            <div class="container">
                {% for training in unfinished_trainings %}
                <div class="row unfinished">
                    <a href="{% url 'tasks:training' training.id %}">{{ training }}</a>
                    <div class="progress">
                        <div class="progress-bar bg-progress" role="progressbar"
                             style="width: {{ training.percent_progress }}%"
                             aria-valuenow="{{ training.percent_progress }}" aria-valuemin="0" aria-valuemax="100">
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if unfinished_trials|length > 0 %}
            <div class="row unfinished_trials">
                <h4>Unfinished trials:</h4>
                <div class="container">
                    {% for trial in unfinished_trials %}
                    <div class="row unfinished">
                        <a href="{% url 'tasks:trial' trial.id %}">{{ trial }}</a>
                        <div class="progress">
                            <div class="progress-bar bg-progress" role="progressbar"
                                 style="width: {{ trial.percent_progress }}%"
                                 aria-valuenow="{{ trial.percent_progress }}"
                                 aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#profile a').addClass('active');
        });
    </script>
{% endblock %}

templates/accounts/settings.html
{% extends "base.html" %}
{% block head_title %}
    Settings
{% endblock %}
{% block left_colon %}
    <div class="container links-div">
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:get_profile' %}">Profile</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="/groups/">Groups</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:statistics' %}">Statistics</a>
        </div>
        <div class="row">
            <a class="left-colon-link active" href="{% url 'accounts:settings' %}">Settings</a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row settings-row">
            <label>
                First name: <input id="first-name" type="text" value="{{ user.first_name }}">
            </label>
        </div>
        <div class="row settings-row">
            <label>
                Last name: <input id="last-name" type="text" value="{{ user.last_name }}">
            </label>
        </div>
        <div class="row settings-row">
            <label>
                Username: <input id="username" type="text" value="{{ user.username }}">
            </label>
        </div>
        <div class="row settings-row buttons-row">
            <input class="btn btn-outline-success" type="button" value="Save" onclick="save_settings()">
        </div>

        <div class="row settings-row">
            <a href="{% url 'account_email' %}">Change e-mail</a>
        </div>
        <div class="row settings-row">
            <a href="{% url 'account_change_password' %}">Change password</a>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getCookie('csrftoken');

    function save_settings() {
        const jq = $.ajax({
            url: "",
            method: "post",
            async: true,
            data: {
                csrfmiddlewaretoken: getCookie('csrftoken'),
                'username': $('#username')[0].value,
                'lastname': $('#last-name')[0].value,
                'firstname': $('#first-name')[0].value,
            },
            contentType: "application/x-www-form-urlencoded"
        });
        jq.done(function(data){
            for (let message of data['my_messages']) {
                $('div.message-container')[0].innerHTML += '<div class="row message-row">' + message + '</div>'
            }
        });
    }

    $(document).ready(function() {
            $('li#profile a').addClass('active');
        });
    </script>
{% endblock %}

templates/accounts/statistics.html
{% extends "base.html" %}
{% block left_colon %}
<div class="container links-div">
    <div class="row">
        <a class="left-colon-link" href="{% url 'accounts:get_profile' %}">Profile</a>
    </div>
    <div class="row">
        <a class="left-colon-link" href="/groups/">Groups</a>
    </div>
    <div class="row">
        <a class="left-colon-link active" href="{% url 'accounts:statistics' %}">Statistics</a>
    </div>
    <div class="row">
        <a class="left-colon-link" href="{% url 'accounts:settings' %}">Settings</a>
    </div>
</div>
{% endblock %}
{% block headtitle %}
    Statistics
{% endblock %}
{% block content %}
    <div class="container">
        {% if training_words|make_list|length > 0 %}
        <div class="row">
            <h4>Trainings</h4>
            <table>
                <tr>
                    <th>{{ language1|title }}</th>
                    <th>{{ language2|title }}</th>
                    <th> Right</th>
                    <th> Total</th>
                    <th> Percent</th>
                </tr>
                {% for word, statistic in training_words %}
                <tr>
                    <td>{{ word.language1.1 }}</td>
                    <td>{{ word.language2.1 }}</td>
                    <td>{{ statistic.right }}</td>
                    <td>{{ statistic.total }}</td>
                    <td>{{ statistic.percent }}%</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
    <hr>
        {% if trial_words|length > 0 %}
            <div class="row">
                <h4>Trials</h4>
                <table>
                    <tr>
                        <th>{{ language1|title }}</th>
                        <th>{{ language2|title }}</th>
                        <th> Right</th>
                        <th> Total</th>
                        <th> Percent</th>
                    </tr>
                    {% for word, statistic in trial_words %}
                    <tr>
                        <td>{{ word.language1.1 }}</td>
                        <td>{{ word.language2.1 }}</td>
                        <td>{{ statistic.right }}</td>
                        <td>{{ statistic.total }}</td>
                        <td>{{ statistic.percent }}%</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#profile a').addClass('active');
        });
    </script>
{% endblock %}

templates/accounts/statistics_dict.html
{% extends "base.html" %}
{% block head_title %}
Statistics
{% endblock %}
{% block left_colon %}
<div class="container links-div">
    <div class="row">
        <a class="left-colon-link" href="{% url 'accounts:get_profile' %}">Profile</a>
    </div>
    <div class="row">
        <a class="left-colon-link" href="/groups/">Groups</a>
    </div>
    <div class="row">
        <a class="left-colon-link active" href="{% url 'accounts:statistics' %}">Statistics</a>
    </div>
    <div class="row">
        <a class="left-colon-link" href="{% url 'accounts:settings' %}">Settings</a>
    </div>
</div>
{% endblock %}
{% block title %}
    Statistics
{% endblock %}
{% block content %}
    <div class="container">
        {% if dictionaries|make_list|length > 0 %}
        <div class="row">
            <h4>Used dictionaries</h4>
            {% for dictionary in dictionaries %}
                <div class="row dict-box">
                    <div class="container">
                        <div class="row">
                            <div class="col-9">
                                <div class="row">
                                    <a class="dict-link" href="{% url 'accounts:statistic_dict' dictionary.id %}">{{ dictionary.title }}</a>
                                </div>
                                {% if dictionary.description|length > 0 %}
                                    <div class="row small">
                                        {{ dictionary.description }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-3">
                                <div class="row">
                                    <input class="btn btn-outline-success" type="button" value="Open"
                                           onclick="openDictionary({{ dictionary.id }})">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        function openDictionary(dictionary_id) {
            document.location.href = '/accounts/profile/statistic_dict/' + dictionary_id + '/';
        }

        $(document).ready(function() {
            $('li#profile a').addClass('active');
        });
    </script>
{% endblock %}