accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.get_profile, name='get_profile'),
    path('settings/', views.settings, name='settings'),
    path('statistics/', views.statistics, name='statistics'),
    path('statistic_dict/<int:dict_id>/', views.statistic_dict, name='statistic_dict'),
]

foreign_words/urls.py
from django.contrib import admin
from django.urls import path, include

from foreign_words import views

urlpatterns = [
    path('', views.main_page),
    path('help/', views.help_page),
    path('admin/', admin.site.urls),
    path('tasks/', include(('tasks.urls', 'tasks'), namespace='tasks')),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
    path('dictionaries/', include(('dictionaries.urls', 'dictionaries'), namespace='dictionaries')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('accounts.urls')),
]

groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'
urlpatterns = [
    path('', views.get_groups, name='get_groups'),
    path('create_group/', views.create_group, name='create_group'),

    path('<int:group_id>', views.group_page, name='group_page'),
    path('<int:group_id>/join_group/', views.join_group, name='join_group'),
    path('<int:group_id>/leave_group/', views.leave_group, name='leave_group'),
    path('<int:group_id>/participants/', views.group_participants, name='participants'),
    path('<int:group_id>/add_student/', views.add_student, name='add_student'),
    path('<int:group_id>/dictionaries/', views.choose_group_dictionary, name='group_dictionaries'),
    path('<int:group_id>/create_dictionary/', views.create_group_dictionary, name='create_group_dictionary'),
    path('<int:group_id>/create_task/', views.create_task, name='create_task'),
    path('<int:group_id>/delete_task/<int:task_id>', views.delete_task, name='delete_task'),

    path('<int:group_id>/rating/', views.get_rating_data, name='get_rating_data'),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('choose_dictionary/', views.choose_dictionary, name='exercises'),

    path('create_exercise/<int:dict_id>/', views.create_exercise, name='create_exercise'),

    path('training/<int:pk>/', views.training, name='training'),
    path('training/<int:pk>/next', views.training_next, name='training_next'),
    path('training/<int:pk>/result', views.show_results, name='show_results'),

    path('trial/<int:pk>/', views.trial, name='trial'),
    path('trial/<int:pk>/next', views.trial_next, name='trial_next'),
    path('trial/<int:pk>/result', views.show_trial_results, name='show_trial_results'),
]

groups/models.py
from __future__ import annotations

from django.contrib.auth.models import User
from django.db import models

from users.models import Person


class Group(models.Model):
    title: str = models.CharField(max_length=200)
    students = models.ManyToManyField('users.Person', related_name='+')
    teacher: Person = models.ForeignKey('users.Person', on_delete=models.CASCADE, blank=True, null=True)

    description: str = models.CharField(max_length=1000, default='')

    is_private: bool = models.BooleanField(default=False)
    creator: Person = models.ForeignKey('users.Person', on_delete=models.CASCADE,
                                        blank=True, null=True, related_name='creator')

    def contains_user(self, user: User):
        return user in self.students.all() or user == self.teacher

    def __contains__(self, item: User) -> bool:
        return self.contains_user(item)

    def __repr__(self) -> str:
        return 'Group(title={})'.format(self.title)

    def __str__(self) -> str:
        return 'Group: {}'.format(self.title)

groups/forms.py
import datetime

from django import forms
from django.utils import timezone

from dictionaries.models import Dictionary


class CreateGroupForm(forms.Form):
    title: str = forms.CharField(label='Title', max_length=200)
    description: str = forms.CharField(label='Description', required=False, max_length=1000)
    is_private: bool = forms.BooleanField(label='Private', required=False)


class AddStudentForm(forms.Form):
    username: str = forms.CharField(label='Username', max_length=100)


class CreateTaskForm(forms.Form):
    title: str = forms.CharField(label='Title', max_length=200)
    creation_time: datetime.datetime = forms.DateTimeField(label='Start',
                                                           initial=timezone.now())
    deadline: datetime.datetime = forms.DateTimeField(label='Deadline',
                                                      initial=timezone.now() + datetime.timedelta(days=7))
    dictionary: Dictionary = forms.ModelChoiceField(label='Dictionary', queryset=None)

    def __init__(self, dictionaries, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dictionary'].queryset = dictionaries

groups/views.py
import datetime
from random import randint, seed

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.utils import timezone
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from icecream import ic

from groups.form_handler import FormHandler
from groups.forms import CreateGroupForm, AddStudentForm, CreateTaskForm
from groups.models import Group
from dictionaries.form_handler import FormHandler as DictionaryFormHandler
from groups.form_handler import FormHandler as TasksFormHandler
from dictionaries.forms import CreateDictionaryForm
from dictionaries.models import Dictionary
from tasks.models import Task, RatingData
from users.models import Person


@login_required
@require_GET
def get_rating_data(request, group_id) -> JsonResponse:
    group: Group = Group.objects.get(id=group_id)
    time: int = 10
    rating_data: RatingData = RatingData(group, time)
    person_progresses: dict[Person, list[(int, int, int)]] = {
        person: rating_data.get_progress(person)
        for person in group.students.all()
    }
    max_progress: list = [max(progress[i][0] for progress in person_progresses.values()) for i in range(time)]

    def calc_progress(progress: (int, int, int), day: int) -> float:
        return 0 if progress[1] == 0 or max_progress[day] == 0 else\
            (progress[0] / progress[1]) * (progress[0] / max_progress[day]) * 5

    def generate_color(key: int) -> str:
        seed(77*key)
        return 'rgba({}, {}, {}, 0.2)'.format(*[randint(0, 255) for _ in range(3)])

    return JsonResponse({
        'dates': [(timezone.now() - datetime.timedelta(days=days)).date() for days in range(time - 1, -1, -1)],
        'dataset': [{
            'label': person.username if not person.first_name else person.first_name,
            'type': 'line',
            'borderColor': generate_color(key),
            'backgroundColor': generate_color(key),
            'data': [calc_progress(person_progresses[person][day], day) for day in range(time-1, -1, -1)],
            }
            for key, person in enumerate(person_progresses.keys())
        ]
    })


@login_required
@require_GET
def get_groups(request):
    user: User = request.user
    groups: list[Group] = list(filter(lambda g: user in g, Group.objects.all()))
    public_groups: list[Group] = list(filter(lambda g: user not in g, Group.objects.filter(is_private=False)))
    return render(request, 'groups/group_list.html', {'groups': groups, 'public_groups': public_groups})


@login_required
@require_GET
def group_page(request, group_id):
    user: User = request.user
    person: Person = Person.objects.get(id=user.id)
    group: Group = Group.objects.get(id=group_id)
    if user in group:
        tasks: list[Task] = Task.objects.filter(group=group,
                                                deadline__gt=timezone.now(),
                                                creation_time__lt=timezone.now())
        tasks_with_progress: list[(Task, int)] = [(task, task.calculate_progress(person)) for task in tasks]
        return render(request, 'groups/group_page.html', {
            'group': group,
            'new_tasks': tasks_with_progress,
        })
    else:
        return Http404


@login_required
@require_http_methods(['DELETE'])
def delete_task(request, group_id, task_id):
    user: User = request.user
    group: Group = Group.objects.get(id=group_id)
    if user in group:
        if len(list(Task.objects.filter(id=task_id, group=group))) == 1:
            task: Task = Task.objects.get(id=task_id)
            task_id: int = task.id
            task.delete()
            messages.add_message(request, messages.INFO, 'Task was deleted')
            return JsonResponse({'status': 'ok', 'task_id': task_id})
        else:
            messages.add_message(request, messages.INFO, 'This task does not exists')
            return JsonResponse({'status': 'error'})
    return Http404


@login_required
@require_GET
def choose_group_dictionary(request, group_id):
    user: User = request.user
    group: Group = Group.objects.get(id=group_id)
    if user in group:
        return render(request, 'exercises/choose_dictionary.html',
                      {'dictionaries': Dictionary.objects.filter(group=group),
                       'group': group
                       })
    else:
        return Http404


@login_required
@require_http_methods(['GET', 'POST'])
def create_group_dictionary(request, group_id):
    group: Group = Group.objects.get(id=group_id)
    user: User = request.user
    if user in group:
        if request.method == 'POST':
            form: CreateDictionaryForm = CreateDictionaryForm(request.POST, request.FILES, group)
            if form.is_valid():
                DictionaryFormHandler.save_dictionary(form, group)
                return HttpResponseRedirect('/groups/{group_id}/dictionaries/'.format(group_id=group_id))
        else:
            form: CreateDictionaryForm = CreateDictionaryForm()
            return render(request, 'dictionaries/create_dictionary.html', {'form': form})


@login_required()
@require_http_methods(['GET', 'POST'])
def create_group(request):
    user: User = request.user
    person: Person = Person.objects.get(email=user.email)
    if request.method == 'POST':
        form: CreateGroupForm = CreateGroupForm(request.POST)
        if form.is_valid():
            FormHandler.create_group(person, form)
            return HttpResponseRedirect('/groups/')
    else:
        form: CreateGroupForm = CreateGroupForm()
        return render(request, 'groups/create_group.html', {'form': form})


@login_required
@require_GET
def group_participants(request, group_id):
    group: Group = Group.objects.get(id=group_id)
    return render(request, 'groups/group_participants.html', {'group': group})


@login_required()
@require_http_methods(['GET', 'POST'])
def add_student(request, group_id):
    group: Group = Group.objects.get(id=group_id)
    if request.method == 'POST':
        form: AddStudentForm = AddStudentForm(request.POST)
        if form.is_valid():
            username: str = form.cleaned_data['username']
            if len(Person.objects.filter(username=username).all()) == 1:
                group.students.add(Person.objects.get(username=username))
                return HttpResponseRedirect('/groups/{}'.format(group_id))
            else:
                return render(request, 'groups/add_student.html',
                              {'form': form, 'group': group,
                               'messages': ['No students has a username {}'.format(username)]})
    else:
        form: AddStudentForm = AddStudentForm()
        return render(request, 'groups/add_student.html', {'form': form, 'group': group})


@login_required
@require_GET
def join_group(request, group_id):
    user: User = request.user
    person: Person = Person.objects.get(email=user.email)
    group: Group = Group.objects.get(id=group_id)
    group.students.add(person)
    group.save()
    messages.add_message(request, messages.INFO, 'You have joined "{}"'.format(group.title))
    return HttpResponseRedirect('/groups/{}'.format(group_id))


@login_required
@require_GET
def leave_group(request, group_id):
    user: User = request.user
    person: Person = Person.objects.get(email=user.email)
    group: Group = Group.objects.get(id=group_id)
    group.students.remove(person)
    group.save()
    messages.add_message(request, messages.INFO, 'You left "{}"'.format(group.title))
    return HttpResponseRedirect('/groups/')


@login_required
@require_http_methods(['GET', 'POST'])
def create_task(request, group_id):
    group: Group = Group.objects.get(id=group_id)
    user: User = request.user
    person: Person = Person.objects.get(id=user.id)
    dictionaries: list[Dictionary] = Dictionary.objects.filter(group=group)
    if user in group:
        if request.method == 'POST':
            form: CreateTaskForm = CreateTaskForm(dictionaries, request.POST)
            if form.is_valid():
                TasksFormHandler.create_task(person, group, form)
                return HttpResponseRedirect('/groups/{group_id}'.format(group_id=group_id))
        else:
            form: CreateTaskForm = CreateTaskForm(dictionaries)
            return render(request, 'groups/create_task.html', {'form': form})

templates/groups/add_student.html
{% extends "base.html" %}
{% block head_title %} Add student to {{ group.title }} {% endblock %}
{% block left_colon %}
    <div class="container links-div">
    <div class="row">
        <a href="{% url 'groups:group_page' group.id %}">Back to the group page</a>
    </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container my-form-container">
    <div class="container">
        <h1>Add student by username</h1>
        <div class="row">
            <form action="" method="post" enctype="multipart/form-data" data-ajax="false">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="row">
                    <div class="col-5">
                        <div class="row">
                            <button class="btn btn-sm btn-outline-primary" type="submit">Submit</button>
                        </div>
                    </div>
                    <div class="col-2"></div>
                    <div class="col-5">
                        <div class="row">
                            <button class="btn btn-sm btn-outline-danger" type="reset">Reset</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}

templates/groups/create_group.html
{% extends "base.html" %}
{% block head_title %} Create group {% endblock %}
{% block content %}
    <div class="container my-form-container">
    <div class="container">
        <h1>Create group</h1>
    <div class="row">
        <form action="" method="post" enctype="multipart/form-data" data-ajax="false">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="row">
                <div class="col-5">
                    <div class="row">
                    <button class="btn btn-sm btn-outline-primary" type="submit">Submit</button>
                    </div>
                </div>
                <div class="col-2"></div>
                <div class="col-5">
                    <div class="row">
                    <button class="btn btn-sm btn-outline-danger" type="reset">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}

templates/groups/create_task.html
{% extends "base.html" %}
{% block head_title %} Create task {% endblock %}
{% block content %}
    <div class="container my-form-container">
    <div class="container">
    <h1>Create task</h1>
        <div class="row">
            <form action="" method="post" enctype="multipart/form-data" data-ajax="false">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="row">
                    <div class="col-5">
                        <div class="row">
                            <button class="btn btn-sm btn-outline-primary" type="submit">Submit</button>
                        </div>
                    </div>
                    <div class="col-2"></div>
                    <div class="col-5">
                        <div class="row">
                            <button class="btn btn-sm btn-outline-danger" type="reset">Reset</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}

templates/groups/group_list.html
{% extends "base.html" %}
{% block head_title %} Groups {% endblock %}
{% block left_colon %}
    <div class="container links-div">
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:get_profile' %}">Profile</a>
        </div>
        <div class="row">
            <a class="left-colon-link active" href="/groups/">Groups</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href={% url 'groups:create_group' %}>Create group</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:statistics' %}">Statistics</a>
        </div>
        <div class="row">
            <a class="left-colon-link" href="{% url 'accounts:settings' %}">Settings</a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
    {% if groups|length > 0 %}
    <h4>Your groups:</h4>
        <div class="container">
            {% for group in groups %}
                <div class="row">
                <div class="group-box">
                    <div class="row">
                        <div class="col-9">
                            <div class="row">
                                <a class="group-link" href="{% url 'groups:group_page' group.id %}">{{ group.title }}</a>
                            </div>
                            <div class="row small">
                                {% if group.description|length > 0 %}
                                {{ group.description }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="row">
                                <input class="group-buttons btn btn-sm btn-outline-success" type="button" value="Open"
                                       onclick="openGroup({{ group.id }})">
                            </div>
                            <div class="row">
                                <input class="group-buttons btn btn-sm btn-outline-danger" type="button" value="Leave"
                                       onclick="leaveGroup({{ group.id }})">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h4>Your are not a member of any group</h4>
    {% endif %}
    </div>
    {% if public_groups|length > 0 %}
    <hr>
    <div class="row">
        <div class="row">
            <h4>Open groups:</h4>
        </div>
        <div class="container">
            {% for group in public_groups %}
                <div class="row">
                <div class="group-box public-group-box">
                    <div class="row">
                        <div class="col-9">
                            <div class="row">
                                <a class="group-link" href="{% url 'groups:join_group' group.id %}">{{ group.title }}</a>
                            </div>
                            {% if group.description|length > 0 %}
                            <div class="row small">
                                    {{ group.description }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="col-3">
                            <div class="row">
                                <input class="group-buttons btn btn-sm btn-outline-success" type="button" value="Join"
                                       onclick="joinGroup({{ group.id }})">
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
    function openGroup(group_id) {
        document.location.href = '/groups/' + group_id;
    }

    function joinGroup(group_id) {
        document.location.href = '/groups/' + group_id + '/join_group/';
    }

    function leaveGroup(group_id) {
        document.location.href = '/groups/' + group_id + '/leave_group/';
    }

    $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}

templates/groups/group_page.html
{% extends "base.html" %}
{% block head_title %} {{ group.title }} {% endblock %}
{% block extra_styles %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.js" crossorigin="anonymous"></script>
{% endblock %}
{% block left_colon %}
    <div class="container links-div">
        <div class="row">
            <a class="left-colon-link active" href="{% url 'groups:group_page' group.id %}">{{ group.title }}</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href="{% url 'groups:group_dictionaries' group.id %}">Group dictionaries</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href="{% url 'groups:create_group_dictionary' group.id %}">Create dictionary</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href="{% url 'groups:create_task' group.id %}">Create task</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href="{% url 'groups:participants' group.id %}">Participants</a>
        </div>
        <div class="row">
            <a class="left-colon-link second-class" href="{% url 'groups:add_student' group.id %}">Add new student</a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
        <h3>{{ group.title }}</h3>
        <small>{{ group.description }}</small>
    </div>
    <div class="row rating">
        <canvas id="myChart" width="400" height="300"></canvas>
<script>
    function getRating() {
        const jq = $.ajax({
            url: "{{ group.id }}/rating/",
            method: "get",
            async: true,
        });
        jq.done(function(data) {
            let rating = data['dataset'];
            let dates = data['dates']
            console.log(dates)

            let ctx = document.getElementById('myChart').getContext('2d');
            let myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    datasets: rating,
                    labels: dates,
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    },
                    title: {
                        display: true,
                        text: 'Rating',
                        fontSize: 25
                    }
                }
            });
        });
    }
    getRating();
</script>
    </div>
    <div class="row tasks">
        {% if new_tasks|length > 0 %}
            {% for task, progress in new_tasks %}
                <div class="container task-box" id="task_{{ task.id }}">
                    <div class="row">
                        <div class="col-9">
                            <div class="row">
                                <strong>{{ task.title }} </strong>
                            </div>
                            <div class="row">
                                <small>Deadline: {{ task.deadline }}</small>
                                <small><a href="{% url 'tasks:create_exercise' task.dictionary.id %}">{{ task.dictionary }}</a></small>
                            </div>
                        </div>
                        <div class="col-3">
                            {% if user.id == task.creator_id %}
                            <div class="row">
                                <input class="group-buttons btn btn-sm btn-outline-danger" type="button" value="Delete"
                                       onclick="deleteTask({{ task.id }})">
                            </div>
                            {% endif %}
                        </div>
                    </div>
                <div class="row">
                    <div class="progress" id="task-progress">
                        <div class="progress-bar bg-info" role="progressbar"
                             style="width: {{ progress }}%;" aria-valuenow="{{ progress }}"
                             aria-valuemin="0" aria-valuemax="100">{{ progress }}%</div>
                    </div>
                </div>
                </div>
            {% endfor %}
        {% else %}
        New tasks will be displayed here.
        {% endif %}
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
    // using jQuery
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }

    let csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    function deleteTask(task_id) {
        const jq = $.ajax({
            url: "/groups/{{ group.id }}/delete_task/" + task_id,
            method: "delete",
            data: {
                csrfmiddlewaretoken: getCookie('csrftoken'),
            },
            async: true,
        });
        jq.done(function(data){
            if (data['status'] === 'ok') {
                $('#task_'+data['task_id']).remove()
            }
        });
    }
    $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}

templates/groups/group_participants.html
{% extends "base.html" %}
{% block head_title %} {{ group.title }} {% endblock %}
{% block left_colon %}
    <div class="links-div container">
    <div class="row">
        <a class="left-colon-link" href="{% url 'groups:add_student' group.id %}">Add new student</a>
    </div>
    <div class="row">
        <a class="left-colon-link" href="{% url 'groups:group_page' group.id %}">Back to the group page</a>
    </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
    <h4>Students:</h4>
    <ul>
        {% for student in group.students.all %}
            <li>
            {% if student.first_name|length > 0 and student.last_name|length > 0 %}
                {{ student.first_name }} {{ student.last_name }}
            {% else %}
                {{ student.username }}
            {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if group.teacher %}
    <h4>Teacher:</h4>
    {{ group.teacher }}
    {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function() {
            $('li#groups a').addClass('active');
        });
    </script>
{% endblock %}